version: '2'

services:

  # statsd-tg -c counters_num -t timers_num -g gauges_num -s sets_num -S set_size -d dest -D dport -T threads_num
  statsd-tg:
    image: statsd-tg:latest
    build: ./statsd-tg
    depends_on:
    - graphite
    - grafana
    command: sh -c "sleep 300 && ./statsd-tg -d graphite -D 8125 -T 1"

  graphite:
    #image: graphiteapp/graphite-statsd:latest
    image: 1e433828fdcf
    ports:
    - 80:80
    - 2003:2003
    - 8125:8125/udp
    volumes:
    - ./storage:/opt/graphite/storage
    environment:
    - COLLECTD=1
    - GRAPHITE_DEBUG=1
    - REDIS_TAGDB=1
#    - BRUBECK=1

  grafana:
    image: grafana/grafana:6.4.3
    ports:
    - 3000:3000
    volumes:
    - ./grafana.json:/usr/share/grafana/public/dashboards/home.json:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  grafana_bootstrap:
    image: haggar:latest
    entrypoint: /bin/sh
    depends_on:
    - grafana
    volumes:
    - ./grafana-bootstrap.sh:/grafana-bootstrap.sh:ro
    command: >
      -c '/grafana-bootstrap.sh'
